blueprint:
  name: Tesco DODO tracking code -> input_text (IMAP)
  description: >
    IMAP (imap_content) eseményből kinyeri a https://t.idodo.group/XXXXXXXX (8 karakter) kódot,
    és beírja egy input_text segédbe. Forwardolt levelekre is jó (a link a body-ban van).
  domain: automation
  input:
    imap_entry_id:
      name: IMAP entry_id
      description: Az IMAP integráció entry_id-ja (Developer Tools -> Events payloadból).
      selector:
        text:
    target_input_text:
      name: Cél input_text
      description: Ide írja be a tracking code-ot.
      selector:
        entity:
          domain: input_text
    subject_must_contain:
      name: Tárgyszűrő (opcionális)
      description: Ha nem üres, csak akkor fut, ha a tárgy tartalmazza ezt a szöveget.
      default: "DODO"
      selector:
        text:
    require_idodo_link:
      name: Kötelező legyen idodo link
      description: Ha true, csak akkor fut, ha talál idodo linket a body-ban.
      default: true
      selector:
        boolean:

mode: single

trigger:
  - platform: event
    event_type: imap_content

variables:
  entry_id_in: !input imap_entry_id
  subject_must_contain_in: !input subject_must_contain
  require_idodo_link_in: !input require_idodo_link

  ev_entry_id: "{{ trigger.event.data.entry_id | default('') }}"
  subject: "{{ trigger.event.data.subject | default('') }}"
  text: "{{ trigger.event.data.text | default('') }}"

  tracking_code: >-
    {%- set m = (text | regex_findall('t\\.idodo\\.group/([A-Za-z0-9]{8})')) -%}
    {{ (m[0] if (m is iterable and (m|length)>0) else '') }}

condition:
  - condition: template
    value_template: "{{ ev_entry_id == entry_id_in }}"
  - condition: template
    value_template: >-
      {{ (subject_must_contain_in | length == 0) or (subject is string and (subject_must_contain_in in subject)) }}
  - condition: template
    value_template: >-
      {{ (not require_idodo_link_in) or (tracking_code | length == 8) }}

action:
  - service: input_text.set_value
    target:
      entity_id: !input target_input_text
    data:
      value: "{{ tracking_code }}"
