blueprint:
  name: Tesco DODO tracking code -> input_text (IMAP)
  description: >
    Extracts the 8-character tracking code from the DODO email and writes it into an input_text helper.
    Works with the IMAP integration event: imap_content.
  domain: automation
  input:
    imap_entry_id:
      name: IMAP entry_id
      description: The IMAP integration entry_id that triggers the imap_content event.
      selector:
        text: {}
    input_text_entity:
      name: input_text entity
      description: The helper where the 8-character tracking code will be stored.
      selector:
        entity:
          domain: input_text
    subject_must_contain:
      name: Subject must contain (optional)
      description: If set, only process emails whose subject contains this substring (case-insensitive).
      default: "DODO"
      selector:
        text: {}
    require_idodo_link:
      name: Require t.idodo.group link
      description: Only run when the email body contains a t.idodo.group link.
      default: true
      selector:
        boolean: {}

mode: single
max_exceeded: silent

trigger:
  - platform: event
    event_type: imap_content

variables:
  entry_id_in: !input imap_entry_id
  subject_must_contain_in: !input subject_must_contain
  require_idodo_link_in: !input require_idodo_link

  ev_entry_id: "{{ trigger.event.data.entry_id | default('') }}"
  subject: "{{ trigger.event.data.subject | default('') }}"
  text: "{{ trigger.event.data.text | default('') }}"

  tracking_code: >-
    {%- set matches = (text | regex_findall('t\.idodo\.group\/?\s*\(?\s*https?:\/\/t\.idodo\.group\/([A-Za-z0-9]{8})', ignorecase=True)) -%}
    {%- if matches and matches[0] -%}
      {{ matches[0] }}
    {%- else -%}
      {%- set m2 = (text | regex_findall('t\.idodo\.group\/([A-Za-z0-9]{8})', ignorecase=True)) -%}
      {{ m2[0] if m2 else '' }}
    {%- endif -%}

condition:
  - condition: template
    value_template: "{{ ev_entry_id == entry_id_in }}"
  - condition: template
    value_template: >
      {% set smc = (subject_must_contain_in | default('')) | string %}
      {% if smc | length == 0 %} true
      {% else %} {{ (subject | lower).find(smc | lower) != -1 }} {% endif %}
  - condition: template
    value_template: >
      {% if not require_idodo_link_in %} true
      {% else %} {{ (text | lower).find('t.idodo.group') != -1 }} {% endif %}
  - condition: template
    value_template: "{{ tracking_code | length == 8 }}"

action:
  - service: input_text.set_value
    target:
      entity_id: !input input_text_entity
    data:
      value: "{{ tracking_code }}"
